@startuml
set namespaceSeparator ::

class "main.dart::MyApp" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "main.dart::MyApp"

class "main.dart::MyHomePage" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "main.dart::MyHomePage"

class "screens::profil.dart::ProfilePage" {
  +Widget build()
  -Container _getAvatar()
  -Container _getCard()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "screens::profil.dart::ProfilePage"

class "screens::quizz.dart::Question" {
  +String questionText
  +bool isCorrect
  +BoxDecoration decoPhoto
}

"screens::quizz.dart::Question" o-- "flutter::src::painting::box_decoration.dart::BoxDecoration"

class "screens::quizz.dart::QuizzPage" {
  +QuizzPageState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "screens::quizz.dart::QuizzPage"

class "screens::quizz.dart::QuizzPageState" {
  +List<Question> questions
  +int indexQuestion
  +int score
  -int _checkAnswer()
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "screens::quizz.dart::QuizzPageState"

class "screens::resultat_quiz.dart::ResultatPage" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "screens::resultat_quiz.dart::ResultatPage"


@enduml